services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@database:5432/postr?sslmode=disable
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - app.env
  database:
    platform: linux/x86_64
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postr
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    expose:
      - 5432
volumes:
  database:
    driver: local
